name: Docker

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SSH_HOST: 192.168.33.10
  DEPLOY_PATH: /opt/myapp

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: [self-hosted, your-label]
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Update Docker images
      run: |
        docker compose -f ${{ env.DEPLOY_PATH }}/docker-compose.yml pull

    - name: Redeploy stack
      run: |
        cd ${{ env.DEPLOY_PATH }}
        docker compose down
        docker compose up -d
