name: Django Docker Deployment

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COMPOSE_FILE: docker-compose.prod.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          buildkitd-config: |
            [registry."ghcr.io"]
              mirrors = ["ghcr.io"]

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/mongg666/django_build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT || 22 }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Starting deployment ==="
            cd /opt/myapp
            docker compose -f ${{ env.COMPOSE_FILE }} pull
            docker compose -f ${{ env.COMPOSE_FILE }} down
            docker compose -f ${{ env.COMPOSE_FILE }} up -d --build
            echo "=== Cleanup old images ==="
            docker image prune -f
