name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]  # Проверьте имя ветки!

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY}}/${{ lower(github.repository) }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secrets
        run: |
          echo "Проверка секретов..."
          [ -z "$SSH_PRIVATE_KEY" ] && echo "Ошибка: SSH_PRIVATE_KEY не задан!" && exit 1
          echo "Начало ключа: ${SSH_PRIVATE_KEY:0:50}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: "localhost"
          port: 2222
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Деплой начат ==="
            cd /opt/myapp
            docker compose up -d
